index.html

I think scribe 101 could be updated and made even easier by adding 'trackbot, end meeting' to the end of the document. But that guide isn't in this repo, so I'm not sure how to edit it.

Link to scribe 101 first - it's more concise and a better starting point

---

index.html

I've added general note saying "The following information in this section is W3C Member-only." to the "News for Chairs, Team Contacts and Editors" section of the index.html file. Also added "(Member-only)" notes to all the Member-only links which didn't have the notes.
In addition, added a missing closing parenthesis ")" to "17 December 2015 (Minutes."

add member-only notes

---

README.md
participant/resources.md

* Add to `participant/resources.md` mentions and hyperlinks to &ldquo;new&rdquo; projects that are related to WG-page development and maintenance
* Add to the list on `README.md` an entry about `participant/resources.md` (it was missing)
* While at it, correct outline of `participant/resources.md` (I take it that &ldquo;Onboarding Information for Group Participants&rdquo; is the title of the page, not a sibling of &ldquo;Group Specific Information&rdquo; and &ldquo;General Information&rdquo;)
Some things I don't understand:
* Why the redundancy with `participant/resources.md` and `participant/resources.html` (here I have edited only the former)? Which one is &ldquo;the source&rdquo;? And how is the other one generated? (Please don't tell me we're keeping the same content in two different …

Point readers to projects related to WG-page development

---

index.html

Mention it in the [News for Chairs, Team Contacts and Editors](https://www.w3.org/Guide/#news) section.

Echidna now supports Candidate Recommendations

---

mock/chairs/advice.md
mock/chairs/buddysystem.md
mock/chairs/index.md
mock/chairs/meetings.md
mock/chairs/starting_a_group.md
mock/chairs/tools.md
mock/editors/index.md
mock/editors/reviewing.md
mock/editors/tools.md
mock/index.md
mock/participants/index.md
mock/participants/invited_experts.md
mock/participants/mailing_lists.md
mock/participants/teleconfs.md
mock/rectrack/index.md

A mock information architecture in which we can start adding in content and further links for the copy sections of /guide.
Kaz and Plh may be able to explain if you need more info!

Information Architecture in /mock

---

index.html

Remove redundancy by consolidating links to groups and resources on the review wiki page.  consolidate links to that wiki page to a single link here.

consolidate links re: horizontal/wide review

---

process/charter.html

Per request from a member during the 2019 Second Screen WG charter review. 
Via @tidoust : The members run lengthy legal processes before they can join a group and typically need to re-run that process when that happens. They could start it before the Call for Participation is issued but for that to happen, they need to know beforehand that this will actually be needed.

Be explicit about likely need to "re-join" a group in call for review

---

index.html

Move things that have been news for a few years into the relevant section of the Guide itself.
Plus a little whitespace tweaking to make the source easier to navigate

Trim the news

---

meetings/continuity.html

The material on how to arrange for virtual presence is more critical than the taxonomy of session types.
Addresses #68

Move the section on meeting formats to the end

---

meetings/continuity.html

Like W3C's Code of Conduct, this document might be of interest to others outside of W3C.  These are some small edits to help in such contexts.

Tweaks to help non-W3C groups

---

chair/role.html
index.html
participant/group.html
participant/groupinfo.js
process/charter.html

This PR fixes a few links and sentences related to legacy content that has now been replaced by new group pages.

New group pages

---

process/banning.html

The added paragraph under the 1st section addresses Tzviya's concern she shared with W3C Management.
Tzviya noted I had omitted to place a link on "ombuds", this PR fixes this as well.

link + caveat

---

process/charter.html

It's no longer in the new group management system. IE application goes through separated app/approval process.

remove "whether the group accepts public IE"

---

meetings/continuity.html

We are conducting distributed workshops now; it's [no longer in the future](https://www.w3.org/Guide/meetings/continuity#workshops).

Update tense of distributed workshop planning

---

process/charter.html

Per [Process 2020](https://www.w3.org/2020/Process-20200915/#CharterReview), changes of Chairs or Team Contacts must be announced to AC.

Charter extension and update

---

process/charter.html

This is intended to help team contacts in managing the time around creating charters and getting them approved by  the W3C Director.

Timeline expectation and guideline for charter creation

---

meetings/organize.html

Proposed rewrites for clarity.  Does not fix the [bullet item I don't understand](https://github.com/w3c/Guide/pull/112#issuecomment-769158287).  
"revisit" was in both the first list - very awkwardly worded - and again _after_ the second list.  I moved it to the top of the doc and deleted the awkward text.  Feel free to rearrange it.
This PR is based on the timezones branch.
[Preview](https://raw.githack.com/w3c/Guide/timezones-2/meetings/organize.html)

clarity rewrites of timezone branch

---

meetings/organize.html

US-style am-pm is especially confusing around midnight and midday.

Use 24 hour clock

---

process/charter.html

@dontcallmedom noted that the instructions to create a group were a bit outdated.
I refreshed those and also removed some legacy text related to the transition to the Patent Policy which had already been commented in the HTML.

Group creation updates

---

process/charter.html

added note: avoid using github.io links for draft charters.

note about draft charter URIs

---

process/charter.html

Updated per November 17, 2021 W3M

Charter extension can only be up to 6 months

---

index.html

The current ["manual"](https://www.w3.org/Guide/meetings/organize.html#calendars) to the group calendaring system is fairly difficult to find; I believe it deserves its explicit link under the 'Running a Meeting' part.

Adding an explicit link to group calendars

---

process/charter.html

This is a proposal to deactivate the old charter when a new charter is valid, for rechartering:
* update the old charter to properly direct people to the latest valid charter.
* end the previous charter in the group admin, so that there won't be two valid charters in parallel (possibly two Patent Policies) which would confuse our spec publication system.

deactivate old charter when new charter is valid

---

participant/group.html

Since all WG/IG/CG/BG should have a calendar page, @pchampin asked if the onboarding page could link to the group's calendar page.
That PR addresses the request.

add group calendar

---

process/charter.html

Following a conversation on slack with @npdoty , it would good to point the AC to the pre-AC review of the charter

Add a link to w3c/strategy when doing AC reviews

---

council/council.html

This adds Council Guide, an HTML version of the AB markdown draft.
It should become live if/when the new Process containing Council is active

Council Guide

---

council/council.html

Process 2023, which defines the Council, is no longer just proposed, and has been formally adopted.

Update guide to match Process 2023 having been adopted

---

council/council.html

... including re-using terminology from the Process Document where relevant to avoid mis-interpretation.

Editorial and quality assurance on council.html

---

process/adv-notice.html
process/charter.html

Replaces https://www.w3.org/2005/09/adv-notice.html
* No need to notify w3m when an advance notice is sent. That should be handle by [TiLT](https://www.w3.org/Guide/teamcontact/tilt.html#communication)
* Removed the note about chairs nomination. Again, that should be handled by TiLT. (ie TiLT should block if the information about the chairs is insufficient).

Moved adv-notice into the Guidebook

---

process/charter.html

I also fixed an anchor for 'TiLT (extra apostrophe).
I think this is right?

There's no more latest guidance from the Director, just TiLT.

---

index.html

The link was to a 2004 document written when the idea of a patent policy was still fairly new.

Remove link to outdated info

---

process/charter.html
process/closing-wg.html

The documentation on closing a WG was Team-only, there was nothing Public.
Process 2023 [adds requirements (AC review, W3C Decision) for early closure](https://www.w3.org/2023/Process-20230612/#GeneralTermination).
The Team-only page remains, it has a different audience and is more about implementing group closure than deciding to close.

Closing wg

---

editor/editors-draft.html
editor/index.html
index.html

This moves:
* https://www.w3.org/2003/Editors/
* https://www.w3.org/2005/03/28-editor-style.html

Move the editors pages into the Guidebook

---

assets/main.css
process/charter-extensions.html
process/charter.html

Moves  https://www.w3.org/2015/04/charter-extensions.html
and assign the role of monitoring charter end dates to Strategy.
fyi @w3c/tilt

Charter extensions

---

process/adv-notice.html

QA and updates (including to ensure matching "excerpted" texts from the process and from the Tips document).
Also, I removed the excerpt from the Process at the bottom section on "background", so that the document is shorter and we have one fewer place to update if the Process text changes. The requirement in question is linked from the top of the doc.

Editorial and QA on adv-notice.html

---

index.html

the "Scribe 101" page is outdated, and has been marked as such. The folloling link "Quick Start Guide" serves a similar purpose, but is more up-to-date.

Remove link to outdated 'Scribe 101' page.

---

process/charter.html

To make the announcement of the new charter smoother, mention that the new charter and the old charter should be in two different URLs.
See also: https://lists.w3.org/Archives/Team/sysreq/2024Oct/0130.html (team-only)

Add URL recommendation for the charter

---

process/charter.html

Since PSIG does not have technical documents nor discussions, it doesn't make sense to do horizontal reviews for it.

No horizontal review for PSIG

---

documentreview/index.html

This makes it clear that horizontal review of proposed amendments is expected.
see also https://github.com/w3c/transitions/issues/682

Horizontal reviews are expected for proposed amendments

---

transitions/index.html
transitions/nextstep.html
transitions/wide-review-request.html

This is not needed anymore as the content is now part of `component--text`
cf https://github.com/w3c/w3c-jekyll-theme/pull/4

Remove custom style that was adding margin/padding between sections

---

manual-of-style/index.html

I ran the link checker on the manual of style.
Note that there are still some broken links as some references appear outdated, but I think those should be addressed in a more in depth review and refresh of this  document.

Fix links in manual of style

---

process/charter.md

Make the following note from the [template announcement](https://www.w3.org/Team/Templates/charter-extension.html) more visible in Guidebook: 
[[
If the group is developing a new charter, link to the GitHub repo where a new charter is being developed and to the issues link to raise comments.
]]

charter extension: indicate whether/where the group is developing a new charter

---

process/charter.md

We're using a WBS questionnaire nowadays open to the entire AC, while the message is targeted to the AC subset who responded to the Call for Review.

Document existing practice to use a questionnaire when making substantive changes to a proposed charter

---

process/adv-notice.md
process/charter.md

In addition to modifying the flow to take into account charter refinement, modified the "advance notice" documentation to account for notification requirements in the Process 2025 draft and created a new (Team-visible) template for creating these announcements.
This pull request should not be merged until the process is updated.

Modified charter howto for charter refinement
