- index.html
I've just substitute the sentence of "Please contact me if you note something that needs urgent attention, or if you want to propose updates." with "Please add your issues to the GitHub repository of this Guidebook if you have specific comments and/or proposals to improve this Guidebook." with the link to the GitHub Issue page (https://github.com/w3c/Guide/issues) because now the Guidebook is on GitHub and issues and proposals should be filed there.
> add a note on GitHub issue page to file issues to improve the Guidebook

- process/charter.html
> Adding the 60 days period

- process/charter.html
See team-only thread in https://lists.w3.org/Archives/Team/w3t-comm/2018Sep/0089.html
> updated to reflect that not just end dates are updated

- chair/buddy.html
Looking forward to finding a mentor!
> Adding my name to the Mentee List

- process/charter.html
stating when existing members don't need to re-join
> 6.1 re-charter announcement

- index.html
I have updated the Guidebook, removing references to tracker.
> Remove tracker infos from the Guidebook

- meetings/continuity.html
> [continuity] Tone down the yelling

- meetings/continuity.html
> those are suggestions

- meetings/continuity.html
It seems important that screen sharing gets its own subtopic paragraph.
> Called out screen sharing issues

- meetings/continuity.html
Intended to help with #77 and #78 .
> Started a video conferencing services section

- meetings/continuity.html
This reformulates the section title.
cc @brewerj
> Avoid the term 'People First'

- meetings/continuity.html
> Explicit consent is required for recordings and screen captures

- process/banning
- process/banning.html
staging W3C guidebook guidelines to suspend or remove participants from groups, per W3M action-2092
> Create "banning" 

- index.html
that adds our newest Guidebook resource to the Guidebook homeapge.
> added link to "banning" under "Process" section

- process/charter.html
specify what/what/when to update group charters following the discussions [[1](https://github.com/w3c/charter-drafts/issues/259), [2](https://github.com/w3c/charter-drafts/pull/272#issuecomment-644377948)].
> propose to refine Charter Update process

- process/charter.html
Fix some editorial nits in the new charter development timeline section.
> Editorial nits in charter.html

- chair/role.html
> Remove gendered language

- index.html
publishing moratoria, 5-year-old announcements of policies.
> remove *very* old news

- meetings/organize.html
... including PLH's full signature with link back to GH
> Editorial pass

- chair/role.html
- meetings/organize.html
This originates from the AB and reusing guidelines proposed by Tatsuya Igarashi.
See [Preview](https://raw.githack.com/w3c/Guide/timezones/meetings/organize.html).
@w3c/advisory-board
> Guidelines for timezones

- meetings/index.html
- meetings/transcripts.html
- meetings/zoom.html
Policy restricting use of automated transcripts.  Also create an index of the several guidebook resources on meetings.
> Add Automated Transcript policy

- process/charter.html
aggregates sections 6.1, 6.2 and 6.3 into one section to match a practice we have adopted in 2015
> propose to aggregate sections 6.1 - 6.3

- meetings/tpac.html
[HTML preview](https://htmlpreview.github.io/?https://github.com/w3c/Guide/blob/good-tpac-2021/meetings/tpac.html)
> Good TPAC meeting

- index.html
To resolve #121.  This is perhaps a clumsy fix, but it's better to not have it at all than to have the problem described in #121
> Comment out news

- incubation.html
I noticed a number of links on this page are outdated/incorrect
> Incubation link updates

- process/charter.html
at @samuelweiler 's suggestion
> Add link to onboarding repo

- process/ac-appeal.html
This is intended to be linked from the W3C Process.
See also https://github.com/w3c/w3process/pull/676
[Preview](https://htmlpreview.github.io/?https://raw.githubusercontent.com/w3c/Guide/ac-appeal/process/ac-appeal.html)
> How to make an AC appeal

- normative-references.html
Update to 2023 Process, Director-free
> Director free

- chair/role.html
Inpput from @plehegar welcome especially on whether we should mention "Strategy and Project Lead" here or we can be less specific
> Update to chair appointment reference and to Chair-Staff Coordination

- process/charter.html
- process/tilt/index.html
Move tilt description and various edits:
* transition requests are in the scope but delegated
* created a GitHub Team for TiLT
* create a GitHub Team for transitions
* other minor edits
cc @w3c/tilt
> More TiLT clarifications

- process/charter.html
Fixes https://github.com/w3c/Guide/issues/184
> reflect director-free; update outdated links

- process/charter.html
> Remove "Director's decision" from the top of charter.html.

- editor/role.html
- index.html
Move content from https://lists.w3.org/Archives/Member/chairs/1999JanMar/0056
> Move editor's role in this repository

- council/council.html
Context: we’re creating a new list for everyone to make comments on new work proposed, and raise/make public formal objections.  This change closes action 3 assigned to @plehegar  to surface it (according to the implementation plan archived at https://lists.w3.org/Archives/Team/w3t-comm/2023Dec/0282.html)
> Augmented "nearby" side menu

- council/council.html
> Add links to the Formal Objection Dashboard

- council/council.html
Address https://github.com/w3c/w3process/issues/735 
following https://github.com/w3c/w3process/pull/808
> Considerations for publishing formal objections.

- chair/role.html
- index.html
- teamcontact/role.html
We use GitHub, there is charter shepherd, etc..
> Validation and refresh on Team contact role

- index.html
- meetings/transcripts.html
- process/joint-deliverables.html
> Renaming of w3process repository

- council/council.html
See also https://github.com/w3c/process/pull/909 and https://github.com/w3c/process/issues/843
> Document what to do if the council gets stuck on procedural questions

- index.html
- process/charter.html
- tools/new-group.html
Since we're setting several new groups, this page could become handy.
> Initial stab at setting up a new group

- index.html
> update media links

- council/council-steps.md
Need to define maximum time for the delay
> archiving Council ML some time after its end

- transitions/index.html
Followup to #338 and addressing #327
> [transitions] Remove extra text
